/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutConversationConversationIDRouteImport } from './routes/_layout.conversation.$conversationID'
import { ServerRoute as ApiProviderServerRouteImport } from './routes/api.provider'
import { ServerRoute as ApiConversationServerRouteImport } from './routes/api.conversation'
import { ServerRoute as ApiConversationConversationIDServerRouteImport } from './routes/api.conversation.$conversationID'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api.auth.$'
import { ServerRoute as ApiConversationConversationIDMessageServerRouteImport } from './routes/api.conversation.$conversationID.message'

const rootServerRouteImport = createServerRootRoute()

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConversationConversationIDRoute =
  LayoutConversationConversationIDRouteImport.update({
    id: '/conversation/$conversationID',
    path: '/conversation/$conversationID',
    getParentRoute: () => LayoutRoute,
  } as any)
const ApiProviderServerRoute = ApiProviderServerRouteImport.update({
  id: '/api/provider',
  path: '/api/provider',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiConversationServerRoute = ApiConversationServerRouteImport.update({
  id: '/api/conversation',
  path: '/api/conversation',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiConversationConversationIDServerRoute =
  ApiConversationConversationIDServerRouteImport.update({
    id: '/$conversationID',
    path: '/$conversationID',
    getParentRoute: () => ApiConversationServerRoute,
  } as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiConversationConversationIDMessageServerRoute =
  ApiConversationConversationIDMessageServerRouteImport.update({
    id: '/message',
    path: '/message',
    getParentRoute: () => ApiConversationConversationIDServerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof SettingsRoute
  '/': typeof LayoutIndexRoute
  '/conversation/$conversationID': typeof LayoutConversationConversationIDRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRoute
  '/': typeof LayoutIndexRoute
  '/conversation/$conversationID': typeof LayoutConversationConversationIDRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/settings': typeof SettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/conversation/$conversationID': typeof LayoutConversationConversationIDRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/settings' | '/' | '/conversation/$conversationID'
  fileRoutesByTo: FileRoutesByTo
  to: '/settings' | '/' | '/conversation/$conversationID'
  id:
    | '__root__'
    | '/_layout'
    | '/settings'
    | '/_layout/'
    | '/_layout/conversation/$conversationID'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}
export interface FileServerRoutesByFullPath {
  '/api/conversation': typeof ApiConversationServerRouteWithChildren
  '/api/provider': typeof ApiProviderServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/conversation/$conversationID': typeof ApiConversationConversationIDServerRouteWithChildren
  '/api/conversation/$conversationID/message': typeof ApiConversationConversationIDMessageServerRoute
}
export interface FileServerRoutesByTo {
  '/api/conversation': typeof ApiConversationServerRouteWithChildren
  '/api/provider': typeof ApiProviderServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/conversation/$conversationID': typeof ApiConversationConversationIDServerRouteWithChildren
  '/api/conversation/$conversationID/message': typeof ApiConversationConversationIDMessageServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/conversation': typeof ApiConversationServerRouteWithChildren
  '/api/provider': typeof ApiProviderServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/conversation/$conversationID': typeof ApiConversationConversationIDServerRouteWithChildren
  '/api/conversation/$conversationID/message': typeof ApiConversationConversationIDMessageServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/conversation'
    | '/api/provider'
    | '/api/auth/$'
    | '/api/conversation/$conversationID'
    | '/api/conversation/$conversationID/message'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/api/conversation'
    | '/api/provider'
    | '/api/auth/$'
    | '/api/conversation/$conversationID'
    | '/api/conversation/$conversationID/message'
  id:
    | '__root__'
    | '/api/conversation'
    | '/api/provider'
    | '/api/auth/$'
    | '/api/conversation/$conversationID'
    | '/api/conversation/$conversationID/message'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiConversationServerRoute: typeof ApiConversationServerRouteWithChildren
  ApiProviderServerRoute: typeof ApiProviderServerRoute
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/conversation/$conversationID': {
      id: '/_layout/conversation/$conversationID'
      path: '/conversation/$conversationID'
      fullPath: '/conversation/$conversationID'
      preLoaderRoute: typeof LayoutConversationConversationIDRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/provider': {
      id: '/api/provider'
      path: '/api/provider'
      fullPath: '/api/provider'
      preLoaderRoute: typeof ApiProviderServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/conversation': {
      id: '/api/conversation'
      path: '/api/conversation'
      fullPath: '/api/conversation'
      preLoaderRoute: typeof ApiConversationServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/conversation/$conversationID': {
      id: '/api/conversation/$conversationID'
      path: '/$conversationID'
      fullPath: '/api/conversation/$conversationID'
      preLoaderRoute: typeof ApiConversationConversationIDServerRouteImport
      parentRoute: typeof ApiConversationServerRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/conversation/$conversationID/message': {
      id: '/api/conversation/$conversationID/message'
      path: '/message'
      fullPath: '/api/conversation/$conversationID/message'
      preLoaderRoute: typeof ApiConversationConversationIDMessageServerRouteImport
      parentRoute: typeof ApiConversationConversationIDServerRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutConversationConversationIDRoute: typeof LayoutConversationConversationIDRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutConversationConversationIDRoute: LayoutConversationConversationIDRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface ApiConversationConversationIDServerRouteChildren {
  ApiConversationConversationIDMessageServerRoute: typeof ApiConversationConversationIDMessageServerRoute
}

const ApiConversationConversationIDServerRouteChildren: ApiConversationConversationIDServerRouteChildren =
  {
    ApiConversationConversationIDMessageServerRoute:
      ApiConversationConversationIDMessageServerRoute,
  }

const ApiConversationConversationIDServerRouteWithChildren =
  ApiConversationConversationIDServerRoute._addFileChildren(
    ApiConversationConversationIDServerRouteChildren,
  )

interface ApiConversationServerRouteChildren {
  ApiConversationConversationIDServerRoute: typeof ApiConversationConversationIDServerRouteWithChildren
}

const ApiConversationServerRouteChildren: ApiConversationServerRouteChildren = {
  ApiConversationConversationIDServerRoute:
    ApiConversationConversationIDServerRouteWithChildren,
}

const ApiConversationServerRouteWithChildren =
  ApiConversationServerRoute._addFileChildren(
    ApiConversationServerRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiConversationServerRoute: ApiConversationServerRouteWithChildren,
  ApiProviderServerRoute: ApiProviderServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
